### PR TITLE
Add long-haul test cases

### PR DESCRIPTION
**Pull request by vinli-cn**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
Enable daily run long-haul test case execution using Github action.

Fault test and Update test are added, but they would be updated further

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by joe-atzinger — APPROVED** [review]

**Comment by andyzhangx** [comment]
could you sign the EasyCLA first?

**Comment by joe-atzinger** [comment]
I signed the CLA.  Hopefully I picked the right org (MS Corp).

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request closed without merging**
